services:
  mysql:
    container_name: 'tp-spring'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=tp-spring'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=spring_user'
    ports:
      - '3306:3306'
